### ISSUE TITLE
Componentes

### ISSUE THREAD

**Issue by andre06santos** [andre06santos/matriculasOn_Front-end#1]
- [x] Criar Button (atributo opcional com _select_)
- [x] Criar Input com _label_ opcional (tipo _text_, _password_, _submit_ e _reset_) e com _Select_ opcional
- [x] Criar Header
- [x] Criar _Layout_

**Comment by Thalis78** [comment]
Acho que seria interessante adicionar um componente footer. Se for decidido, eu faço.
