### ISSUE TITLE
Corrigir CRUD de usuários

### ISSUE THREAD

**Issue by andre06santos** [andre06santos/matriculasOn_Front-end#111]
- [x] Na página de listagem de usuários, incluir o `useEffect()` para obter os dados dos usuários.
- [x] Renomear `getUser` para `getUsers`
- [x] Remover o array provisório `users`

Obs.: Sempre que alterar o código, remova os links de importações desnecessários ao componente.

**Comment by GiseleBCSantos** [comment]
Tasks 1 and 2 completed by @Thalis78 
Task 3 completed in PR #132
