### ISSUE TITLE
Refactor: componente Input

### ISSUE THREAD

**Issue by andre06santos** [andre06santos/matriculasOn_Front-end#31]
Trocar a lógica:
`submitFilter` está sendo passado para `type={type}` e causa erro porque esse tipo não existe no html.
Em vez disso, o `type` deve ficar implícito em `{...rest}`.
Depois, trocar `type = "text"` por `variant`.
O objeto `inputClasses` terá suas chaves alteradas para algo parecido com:
`bgSuccess`, `bgError`, `bgMuted`, `bgAccent`

**Comment by GiseleBCSantos** [comment]
Sistema de variant adicionado ao Input Component

**Comment by GiseleBCSantos** [comment]
bgNeutral = cinza
bgSuccess = verde
bgInfo = lilás
