### ISSUE TITLE
Criar página de listagem de permissões

### ISSUE THREAD

**Issue by andre06santos** [andre06santos/matriculasOn_Front-end#6]
- [x] Implementar o filtro. Obs.: a palavra `Filtro` não é a _label_ do _Input_
- [x] Implementar texto sobre quantidade de resultados encontrados após filtragem
- [x] Criar tabela com o campo _Role_, _Descrição_ e _Ações_
- [x] Implementar a paginação (obs.: fazer isso por último)

**Comment by GiseleBCSantos** [comment]
Todas tarefas feitas.
