### ISSUE TITLE
Validações dos Inputs

### ISSUE THREAD

**Issue by andre06santos** [andre06santos/matriculasOn_Front-end#71]
**Obs.: apenas os campos dos filtros são opcionais!**

- [x] Matrícula (valor diferente de vazio)
- [x] CPF (apenas números)
- [x] Nome (valor diferente de vazio)
- [x] Username (valor diferente de vazio)
- [x] Email (usar regex com padrão `x@x.xx` e trocar o tipo do _Input_ para `email`)
- [x] Curso (valor diferente de vazio)
- [x] Senha (no mínimo 8 caracteres)
- [x] Confirmação de senha (valor igual ao campo senha)
- [x] Status (valor diferente de vazio)
- [x] Cargo (valor diferente de vazio)
- [x] Departamento (valor diferente de vazio)
- [x] Descrição (valor diferente de vazio)
- [x] Role (valor diferente de vazio)

**Comment by GiseleBCSantos** [comment]
Matricula - letras e numeros, max 10
Cpf- 11 numeros
Nome - so ter letras, max 50
Username - pode tudo, max 10
Email - x@x.xx
Curso - diferente de ""
Senha - pode tudo, min 8
ConfSenha - merma coisa
Status - diferente de vazio
Cargo - caracter, max 30
Departamento - caracter, max 30
Descricao - caracter, max 100
Role - nao numeros, max 20

**Comment by GiseleBCSantos** [comment]
Validação implementada em todos formulários
